@startuml
title Building Block View [Level 2] - Infrastructure

skinparam shadowing false
skinparam defaultTextAlignment center
skinparam rectangle {
  RoundCorner 12
}
skinparam package {
  RoundCorner 12
}
skinparam package<<BlackBox>> {
  BackgroundColor black
  BorderColor black
  FontColor white
  FontSize 18
  Padding 60
}
skinparam rectangle<<BlackBox>> {
  BackgroundColor black
  BorderColor black
  FontColor white
  FontSize 18
}
skinparam component<<BlackBox>> {
  BackgroundColor black
  BorderColor black
  FontColor white
  FontSize 16
}

actor "Mitglied" as Member
actor "Trainer" as Trainer

rectangle "Public Training Sheet" as PublicSheet
rectangle "Private Data Sheet" as PrivateSheet

package RSVP {
  package "Application" as Application <<BlackBox>>
  package "Domain" as Domain <<BlackBox>>

  package "Infrastructure" as Infrastructure {
    package "Adapters" as Adapters <<BlackBox>>

    package "Gateway" as Gateway <<BlackBox>>
  }
}

Application ..> Adapters
Adapters ..> Domain
Adapters --> Gateway
Gateway --> PublicSheet
Gateway --> PrivateSheet

Adapters --> Member : <<Mail>> Erinnerung
Adapters --> Trainer : <<Mail>> Teilnehmerliste
@enduml