@startuml
title Building Block View [Level 2] - Configuration and User Integration

skinparam shadowing false
skinparam defaultTextAlignment center
skinparam package {
  RoundCorner 12
}
skinparam package<<BlackBox>> {
  BackgroundColor black
  BorderColor black
  FontColor white
  FontSize 18
  Padding 60
}
skinparam rectangle<<BlackBox>> {
  BackgroundColor black
  BorderColor black
  FontColor white
  FontSize 18
}

package RSVP {
  package "Domain / Ports" as DomainPorts <<BlackBox>>

  package "Infrastructure" as Infrastructure {
    package "Adapters" as Adapters {
      component ConfigurationAdapter
    }

    package "Gateway" as Gateway {
      interface ISheetGateway
      component GoogleSheetGateway
    }
  }
}

rectangle "Private Data Sheet" as PrivateSheet

ConfigurationAdapter ..> DomainPorts
ConfigurationAdapter --> ISheetGateway
GoogleSheetGateway .up.|> ISheetGateway
GoogleSheetGateway --> PrivateSheet
@enduml
