@startuml
title Building Block View [Level 1]

skinparam shadowing false
skinparam defaultTextAlignment center
skinparam rectangle {
  RoundCorner 12
}
skinparam package<<BlackBox>> {
  BackgroundColor black
  BorderColor black
  FontColor white
  FontSize 18
  Padding 60
}

actor "Mitglied" as Member
actor "Trainer" as Trainer
note right of Trainer : Trainer ist \nauch Mitglied

rectangle "Trainings Sheet" as Sheet

package RSVP {
  package Services <<BlackBox>>
  rectangle Formular
  package MailAdapter <<BlackBox>>
  package ResponseHandler <<BlackBox>>
  package TrainingSheetAdapter <<BlackBox>>
  package ConfigurationAdapter <<BlackBox>>
  rectangle Private_Data_Sheet as "Privates Sheet"

  Formular -[hidden]down-> TrainingSheetAdapter
  ResponseHandler -[hidden]down-> TrainingSheetAdapter
  MailAdapter -[hidden]down-> ConfigurationAdapter
}

ConfigurationAdapter ..> Services
TrainingSheetAdapter ..> Services
MailAdapter ..> Services
ResponseHandler ..> Services

Formular --> ResponseHandler : <<Call>> 
Member --> Formular : <<Formular>> Registrierung
MailAdapter --> Member : <<Mail>> Erinnerung
Member --> ResponseHandler : <<Mail Response>> Absage / Zusage

MailAdapter --> Trainer: <<Mail>> Teilnehmerliste

Sheet --> TrainingSheetAdapter : Lesen
TrainingSheetAdapter --> Sheet : Schreiben


ConfigurationAdapter --> Private_Data_Sheet
@enduml
