@startuml
title Context View

left to right direction
skinparam shadowing false
skinparam defaultTextAlignment center
skinparam rectangle {
  RoundCorner 12
}
skinparam package<<BlackBox>> {
  BackgroundColor black
  BorderColor black
  FontColor white
  FontSize 18
  Padding 60
}

actor "Mitglied" as Member
actor "Trainer" as Trainer
note right of Trainer : Trainer ist \nauch Mitglied

rectangle "Trainings Sheet" as Sheet

package "Training-RSVP-System\n\n\n\n" <<BlackBox>> as RSVP {
}

Member --> RSVP : <<Formular>> Registrierung
Member -> RSVP : <<Mail Response>> Absage / Zusage
RSVP --> Member : <<Mail>> Erinnerung

RSVP --> Trainer: <<Mail>> Teilnehmerliste

Sheet -> RSVP
RSVP -> Sheet

@enduml
