// Reads image assets from the assets/ directory and writes them as TypeScript
// string constants to src/runtime/publicAssets.ts.
// Re-run with: npm run gen:assets

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ASSETS_DIR = path.join(ROOT, 'assets');
const OUTPUT_FILE = path.join(ROOT, 'src', 'runtime', 'publicAssets.ts');

const assets = [
  { name: 'FRANCONIA_WELCOME_DATA_URI', file: 'franconia_welcome.webp', mime: 'image/webp' },
  { name: 'FRANCONIA_HAPPY_DATA_URI',   file: 'franconia_happy.webp',   mime: 'image/webp' },
  { name: 'FRANCONIA_SAD_DATA_URI',     file: 'franconia_sad.webp',     mime: 'image/webp' },
];

const lines = [
  '// Generated from assets/ by scripts/inlineAssets.js',
  '// Re-run `npm run gen:assets` if any source file in assets/ changes.',
  '// Do not edit this file manually.',
  '',
];

for (const asset of assets) {
  const filePath = path.join(ASSETS_DIR, asset.file);
  if (!fs.existsSync(filePath)) {
    console.error(`Missing asset file: ${filePath}`);
    process.exit(1);
  }
  const data = fs.readFileSync(filePath).toString('base64');
  const dataUri = `data:${asset.mime};base64,${data}`;
  lines.push(`export const ${asset.name} = '${dataUri}';`);
  const kib = Math.round(data.length * 3 / 4 / 1024);
  console.log(`  ${asset.name}: ${asset.file} → ${kib} KiB encoded`);
}

lines.push('');
fs.writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf8');
console.log(`Written: ${path.relative(ROOT, OUTPUT_FILE)}`);
